export const chapterResponses = {
    data: {
      enrolled: true ,
      courseCompletedStatus: false,
      courseId: "638d6c7fa572c21b9fe07fbd",
      courseName:"Learn Figma - UI/UX Design Essential Training",
      chapterCount: 4,
      lessonCount: 10,
      testCount: 2,
      courseDuration:"00:00:00",
      coursePercentage:39,
      joinedDate:"",
      completedDate:"",
      certificateUrl:"",
      chapterResponses: [
        {
          chapterNumber: 1,
          numberOfLessons: 2,
          chapterName: "Introduction to Course",
          chapterCompletedStatus:true,
          chapterId:"638d6c7fa572c21b9fe07fac",
          lesson: [
            {
              lessonStatus:false,
            lessonCompletedStatus:true,
              serialNumberOfLesson: 1,
              title: "Lesson number 1",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608951/video/ff3q2ypesq1zs1xeldmp.mp4",
              _id: "638d6c7fa572c21b9fe07fad",
              lessonId:"638d6c7fa572c21b9fe07fad",
            },
            {
              lessonStatus:false,
              lessonCompletedStatus:true,
              serialNumberOfLesson: 2,
              title: "Lesson number 2",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608807/video/jltxhohj11f27dm6pxru.mp4",
              _id: "638d6c7fa572c21b9fe07fae",
              lessonId:"638d6c7fa572c21b9fe07fae",
            },
          ],
          _id: "638d6c7fa572c21b9fe07fac",
        },
        {
          chapterNumber: 2,
          numberOfLessons: 3,
          chapterName: "Chapter number 2",
          chapterCompletedStatus:true,
          chapterId:"638d6c7fa572c21b9fe07faf",
          lesson: [
            {
              lessonStatus:false,
              lessonCompletedStatus:true,
              serialNumberOfLesson: 3,
              title: "Lesson number 3",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608951/video/ff3q2ypesq1zs1xeldmp.mp4",
              _id: "638d6c7fa572c21b9fe07fb0",
              lessonId:"638d6c7fa572c21b9fe07fb0",
            },
            {
              lessonStatus:false,
              lessonCompletedStatus:false,
              serialNumberOfLesson: 4,
              title: "Lesson number 4",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608807/video/jltxhohj11f27dm6pxru.mp4",
              _id: "638d6c7fa572c21b9fe07fb1",
              lessonId:"638d6c7fa572c21b9fe07fb1",
            },
            {
              lessonStatus:false,
              lessonCompletedStatus:false,
              serialNumberOfLesson: 5,
              title: "Lesson number 5",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608951/video/ff3q2ypesq1zs1xeldmp.mp4",
              _id: "638d6c7fa572c21b9fe07fb2",
              lessonId:"638d6c7fa572c21b9fe07fb2",
            },
          ],
          _id: "638d6c7fa572c21b9fe07faf",
          test: {
            _id: "638d6c7fa572c21b9fe07fa7",
            testId:"638d6c7fa572c21b9fe07fa7",
            testNumber: 1,
            testTitle: "Chapter 2 Test",
            totalQuestions: 5,
            totalTimeAlloted: "00:00:00",
            chapterTestPercentage:0,
            isFinalTest:false,
          },
        },
        {
          chapterNumber: 3,
          numberOfLessons: 2,
          chapterName: "Chapter number 3",
          chapterCompletedStatus:false,
          chapterId:"638d6c7fa572c21b9fe07fb3",
          lesson: [
            {
              lessonStatus:false,
              lessonCompletedStatus:false,
              serialNumberOfLesson: 6,
              title: "Lesson number 6",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608807/video/jltxhohj11f27dm6pxru.mp4",
              _id: "638d6c7fa572c21b9fe07fb4",
              lessonId:"638d6c7fa572c21b9fe07fb4",
            },
            {
              lessonStatus:false,
              lessonCompletedStatus:false,
              serialNumberOfLesson: 7,
              title: "Lesson number 7",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608951/video/ff3q2ypesq1zs1xeldmp.mp4",
              _id: "638d6c7fa572c21b9fe07fb5",
              lessonId:"638d6c7fa572c21b9fe07fb5",
            },
          ],
          _id: "638d6c7fa572c21b9fe07fb3",
        },
        {
          chapterNumber: 4,
          numberOfLessons: 3,
          chapterName: "Chapter number 4",
          chapterCompletedStatus:false,
          chapterId:"638d6c7fa572c21b9fe07fb6",
          lesson: [
            {
              lessonStatus:false,
              lessonCompletedStatus:false,
              serialNumberOfLesson: 8,
              title: "Lesson number 8",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608807/video/jltxhohj11f27dm6pxru.mp4",
              _id: "638d6c7fa572c21b9fe07fb7",
              lessonId:"638d6c7fa572c21b9fe07fb7",
            },
            {
              lessonStatus:false,
              lessonCompletedStatus:false,
              serialNumberOfLesson: 9,
              title: "Lesson number 9",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608951/video/ff3q2ypesq1zs1xeldmp.mp4",
              _id: "638d6c7fa572c21b9fe07fb8",
              lessonId:"638d6c7fa572c21b9fe07fb8",
            },
            {
              lessonStatus:false,
              lessonCompletedStatus:false,
              serialNumberOfLesson: 10,
              title: "Lesson number 10",
              duration: "00:00:00",
              url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608807/video/jltxhohj11f27dm6pxru.mp4",
              _id: "638d6c7fa572c21b9fe07fb9",
              lessonId:"638d6c7fa572c21b9fe07fb9",
            },
          ],
          _id: "638d6c7fa572c21b9fe07fb6",
          test: {
            _id: "638d6c7fa572c21b9fe07fa9",
            testId:"638d6c7fa572c21b9fe07fa9",
            testNumber: 2,
            testTitle: "Module Test 4",
            totalQuestions: 5,
            totalTimeAlloted: "00:00",
            chapterTestPercentage:0,
            isFinalTest:false,
          },
        },
      ],
    },
  }
  export const courseOverviewData = {
    data: {
      enrolled: true,
      courseName: "Learn Figma - UI/UX Design Essential Training",
      courseId: "638d6c7fa572c21b9fe07fbd",
      chapterCount: 4,
      lessonCount: 10,
      testCount: 3,
      courseDuration: "00:00:00",
      categoryName: "Buisness",
      previewVedio:"https://www.youtube.com/watch?v=30LWjhZzg50",
      courseTagLine:
        "Learn how to design a beautiful and engaging mobile app with Figma. Learn-by-doing approach. Learn how to design a beautiful and engaging mobile app with Figma. Learn-by-doing approach.",
      description:
        "Figma is a very powerful application that runs online. There are virtually no platform boundaries when it comes to using figma because you can design within a web browser or using their desktop application made for windows and macs. Figma is similar to Sketch and Adobe XD but is the more powerful of the three when it comes. Figma is a very powerful application that runs online. There are virtually no platform boundaries when it comes to using figma because you can design within a web browser or using their desktop application made for windows and macs...",
      learningOutCome: [
        "Design Websites",
        "You will have a fully interactive design and prototype at the end of this course",
        "Design mobile and desktop apps",
        "You will learn how to reuse design elements for future projects",
      ],
      requirements: [
        "Internet Access s",
        "You should know your way around computer basic",
        "hdbeci",
      ],
      profilePhoto: "",
      instructorName: "abcj",
      designation: "User Interface teacher",
      url: "twitter account or linkedinaccount anything www.appledesigntips.com",
      instructorDescription:
        "Back in 2010, I started brainspin with a desire to design compelling and engaging apps. For over 7 years, I have designed many high profile web and iPhone applications. The applications range from 3D medical aided web applications to project management applications for niche industries. I am also the founder of a large local design organization, Salt Lake Designers, where I and other local influencers help cultivate the talents of up and coming UX designers through workshops and panel",
    },
  };
  export const continueModalData = {
    pauseTime:"00:00:00",
      chapterNumber: 2,
      lessonNumber:4,
      chapterName:"Chapter number 2",
      lessonName: "Lesson number 4",
      courseId: "638d6c7fa572c21b9fe07fbd",
      chapterId: "638d6c7fa572c21b9fe07faf",
      lessonId: "638d6c7fa572c21b9fe07fb1",
      url: "http://res.cloudinary.com/dghcx4s2l/video/upload/v1669608807/video/jltxhohj11f27dm6pxru.mp4",
  };